logging:
  level:
    root: info
    com.example: trace
    io.debezium.engine: debug
    org.springframework.integration.debezium: trace
server:
  port: 9090
  shutdown: graceful
spring:
  output:
    ansi:
      enabled: always
  elasticsearch:
    uris:
      - http://localhost:19200
  data:
    redis:
      database: 1
      host: localhost
      port: 16379
      password: 123456
      timeout: 10s
      connect-timeout: 10s

debezium:
  connectors:
    - name: task_customer_dev
      offset:
        address: localhost:16379
        database: 1
        password: 123456
        key: task_customer_dev
      database:
        hostname: localhost
        port: 15432
        name: customer_dev
        user: postgres
        password: 123456
        include-tables:
          - customer_dev.public.customer
    - name: task_post_dev
      offset:
        address: localhost:16379
        database: 1
        password: 123456
        key: task_post_dev
      database:
        hostname: localhost
        port: 15432
        name: post_dev
        user: postgres
        password: 123456
        include-tables:
          - post_dev.public.post
