logging:
  level:
    root: info
    com.example: trace
    io.debezium.embedded.async: debug
    org.springframework.data.elasticsearch: debug
server:
  shutdown: graceful
spring:
  output:
    ansi:
      enabled: always
  elasticsearch:
    uris:
      - http://localhost:19200
    connection-timeout: 10s
    socket-keep-alive: true
    socket-timeout: 30s
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      password: 123456
      timeout: 10s
      connect-timeout: 10s

debezium:
  connectors:
    - name: test-alice
      slot-name: slot_alice
      publication-name: publication_alice
      topic-prefix: test
      read-only-connection: true
      offset-storage-file: sd
      database:
        hostname: localhost
        port: 15432
        name: debezium
        user: postgres
        password: 123456
