logging:
  level:
    root: info
    com.example: trace
    io.debezium.embedded.async: debug
    org.springframework.data.elasticsearch: debug
server:
  shutdown: graceful
spring:
  application:
    name: test-debezium
  output:
    ansi:
      enabled: always
  devtools:
    add-properties: true
  lifecycle:
    timeout-per-shutdown-phase: 5s
  elasticsearch:
    uris:
      - http://localhost:19200
      - http://localhost:19201
      - http://localhost:19202
    connection-timeout: 10s
    socket-keep-alive: true
    socket-timeout: 30s
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
      ssl:
        enabled: false
      timeout: 10s
      connection-timeout: 10s
      client-name: test-debezium

debezium:
  connectors:
    - name: test-alice
      slot-name: slot_alice
      publication-name: publication_alice
      topic-prefix: test
      read-only-connection: true
      offset-storage: com.example.debezium.config.offset.RedisOffsetBackingStore
      database:
        user: postgres
        password: 123456
